#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
CREATE USER $DB_APP_USER WITH PASSWORD '$DB_APP_PASSWORD';
GRANT CONNECT ON DATABASE $POSTGRES_DB TO $DB_APP_USER;
GRANT USAGE ON SCHEMA public TO $DB_APP_USER;
GRANT SELECT, INSERT, UPDATE ON measurements TO $DB_APP_USER;
GRANT USAGE, SELECT ON SEQUENCE measurements_id_seq TO $DB_APP_USER;
EOSQL
